### ISSUE TITLE
Index - Admin

### ISSUE THREAD

**Issue by federicoarambillet** [federico37j/proyecto-final#5]
Implementar el HTML, CSS y JS de está pantalla según corresponda, guiándose de la siguiente imagen.

**Comment by federico37j** [comment]
![Uploading index vendedor.png…]()

**Comment by federicoarambillet** [comment]
![index vendedor](https://user-images.githubusercontent.com/42477825/94979503-6f8fe080-04f9-11eb-8863-b65f138a2155.png)
